[package]
name = "capsule"
type = "lib"
version = "0.1.0"
noir_version = "0.10.5"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v0.10.5", directory = "noir-projects/aztec-nr" }